name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Cocos Creator
        run: |
          # Define the Cocos Creator path
          COCOS_CREATOR_PATH=~/CocosCreator/CocosCreator
          
          # Check if Cocos Creator is already installed
          if [ ! -f "$COCOS_CREATOR_PATH" ]; then
            echo "Cocos Creator not found. Downloading..."
            mkdir -p ~/CocosCreator
            
            # Download the Cocos Creator zip file
            curl -L https://download.cocos.com/CocosCreator/v3.8.1/CocosCreator-v3.8.1-mac-101613.zip -o ~/CocosCreator/CocosCreator-v3.8.1.zip
            
            # Install unzip if not available
            sudo apt update
            sudo apt install unzip -y
            
            # Unzip the downloaded file
            unzip ~/CocosCreator/CocosCreator-v3.8.1.zip -d ~/CocosCreator
          else
            echo "Cocos Creator is already installed."
          fi

          - name: Build Web Project
          run: |
            # Build the project for web-mobile platform
            "$COCOS_CREATOR_EXECUTABLE" --path . --build "platform=web-mobile;debug=true"
  
        