name: Build Cocos Creator Project

on:
  push:
    branches:
      - main  # Adjust to your preferred branch

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java
        run: |
          brew install openjdk@11
          echo 'export PATH="/usr/local/opt/openjdk@11/bin:$PATH"' >> $GITHUB_ENV
          brew link --force --overwrite openjdk@11

      - name: Setup Cocos Creator
        run: |
          echo "Downloading Cocos Creator..."
          mkdir -p /Applications
          
          # Download the Cocos Creator zip file
          curl -L https://download.cocos.com/CocosCreator/v3.8.1/CocosCreator-v3.8.1-mac-101613.zip -o /Applications/CocosCreator-v3.8.1.zip
          
          # Unzip the downloaded file directly to /Applications
          unzip /Applications/CocosCreator-v3.8.1.zip -d /Applications

      - name: Build Web Project
        run: |
          # Add Java to PATH
          export PATH="/usr/local/opt/openjdk@11/bin:$PATH"
          
          # Build the project for web-mobile platform
          /Applications/CocosCreator.app/Contents/MacOS/CocosCreator --path ../ --build "platform=web-mobile;debug=true"
        shell: bash

      - name: Build Android Project
        run: |
          # Add Java to PATH
          export PATH="/usr/local/opt/openjdk@11/bin:$PATH"
          
          # Build the project for android platform
          /Applications/CocosCreator.app/Contents/MacOS/CocosCreator --path ../ --build "platform=android;debug=true"
        shell: bash
