name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Cocos Creator
        run: |
          # Create directory for Cocos Creator
          mkdir -p ~/CocosCreator
          
          # Download the Cocos Creator zip file
          curl -L https://download.cocos.com/CocosCreator/v3.8.1/CocosCreator-v3.8.1-mac-101613.zip -o ~/Downloads/CocosCreator-v3.8.1.zip
          
          # Install unzip if not available
          sudo apt update
          sudo apt install unzip -y
          
          # Unzip the downloaded file
          unzip ~/Downloads/CocosCreator-v3.8.1.zip -d ~/CocosCreator

      - name: Build Web Project
        run: |
          # Build the project for web-mobile platform
          ~/CocosCreator/CocosCreator --path . --build "platform=web-mobile;debug=true"

      - name: Build Android Project
        run: |
          # Build the project for android platform
          ~/CocosCreator/CocosCreator --path . --build "platform=android;debug=true"